### ISSUE TITLE
Talk about local helper macros

### ISSUE THREAD

**Issue by Veykril** [Veykril/tlborm#12]
This probably should get its own page in the [minutiae](https://veykril.github.io/tlborm/macros/minutiae.html) category?

See https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros

**Comment by jpmckinney** [comment]
What do you mean by local helper macros? When I follow that link, it doesn't mention "local" or "helper".

**Comment by Veykril** [comment]
Looks like they removed it from the book which makes sense, it's not really necessary nowadays. So I don't think we need this section anymore, for the curious, it's still somewhat explained in the reference https://doc.rust-lang.org/reference/macros-by-example.html#hygiene
