### ISSUE TITLE
Audience expectations

### ISSUE THREAD

**Issue by rajeshk-elyments** [Veykril/tlborm#13]
Note: While i am not experienced enough to contribute by adding content, I can perhaps add value as a reader and mention where the book could improve as seen from a reader's perspective. 

Suggestion: 
Right up top, a note on what prior knowledge is expected from the reader and where you suggest one might go to acquire that knowledge if it ain't already there would be helpful.

**Comment by Veykril** [comment]
Suggestions are definitely helpful, especially from people who aren't well versed with macros yet, as they can give a good viewpoint experienced people cannot give. That suggestion is a good point, I'll add something regarding that.

**Comment by Veykril** [comment]
I added the following snippet to the frontpage: 

> This book expects you to have basic knowledge of Rust, it will not explain language features or constructs that are irrelevant to macros. Having read and understood the first seven chapters of the Rust Book is a must, though having read the majority of the book is recommended.

Let me know if this tells you enough or not.

**Comment by rajeshk-elyments** [comment]
This is definitely useful. 
Also you can add what is not expected. For example, "No prior knowledge of macros is assumed. We will start from the very basics so far as macros are concerned".

**Comment by Veykril** [comment]
That seems like a good addition, thanks!
