### ISSUE TITLE
Status & roadmap?

### ISSUE THREAD

**Issue by d4h0** [Veykril/tlborm#20]
Hi,

First of all, I'd like to thank you for your work, this is fantastic, @Veykril!

It would be great if there was information about the current status of the project, and maybe a roadmap. This would be useful to people who'd like to read the book when it's mostly updated/finished.

This information also would be useful to people who'd like to contribute to the project.

Thanks, again!

**Comment by Veykril** [comment]
Yes I agree, I'll try to compile a list of things that would be nice/are done

**Comment by d4h0** [comment]
Awesome! :)

Maybe you then also could request help in the "help wanted" section of ["This week in Rust"](https://this-week-in-rust.org/), if you don't want to implement these updates yourself?

**Comment by Veykril** [comment]
Yes I definitely wanted to ask if the book can be mentioned there, kind of forgot about it 😅. Opened #21 let me know if I missed anything infowise that should be added there still.

**Comment by d4h0** [comment]
Thanks, @Veykril!

Are there any plans to extend the book with information about Procedural Macros?

If you don't plan this yourself, would you welcome contributions from others?

That would be interesting, I think.

**Comment by Veykril** [comment]
Ah yes, I wanted to open an issue about that as well but forgot, thanks for the reminder 😄. I'm definitely interested in adding that as well. I opened #23 for discussion regarding that.
