### ISSUE TITLE
Why there are nine token trees at the root level in the example of the token trees at the Chapter Source Analysis

### ISSUE THREAD

**Issue by Celthi** [Veykril/tlborm#28]
Hi, I don't quite understand the following sentence in Source Analysis:
`Note that this has no relationship to the AST the expression would produce; instead of a single root node, there are nine token trees at the root level.`

The token tree
«a» «+» «b» «+» «(   )» «+» «e»
          ╭────────┴──────────╮
           «c» «+» «d» «[   ]»
                        ╭─┴─╮
                         «0»
Is it seven? <<a>> <<+>> <<+>> <<()>> <<+>> <<e>>?

**Comment by Veykril** [comment]
That is indeed wrong and should say 7, nice catch! Feel free to change this in a PR otherwise I get to it later today.
