### ISSUE TITLE
[Question] How to draw such a beautiful ASCII chart?

### ISSUE THREAD

**Issue by tan-wei** [Veykril/tlborm#29]
Thanks for the update for tlborm. I have a question which is not related to the content of the book.

We can see such a beautiful ASCII chart in the book, such as:
```
┌─────────┐   ┌─────────┐
│ BinOp   │ ┌╴│ LitInt  │
│ op: Add │ │ │ val: 1  │
│ lhs: ◌  │╶┘ └─────────┘
│ rhs: ◌  │╶┐ ┌─────────┐
└─────────┘ └╴│ LitInt  │
              │ val: 2  │
              └─────────┘
```

So is there any tool to draw this? Or just manually input by ourselves? Thanks very much!

**Comment by Veykril** [comment]
Those were taken over from the original, but so I don't know if a tool was used for them unfortunately but I would believe so.

**Comment by tan-wei** [comment]
OK, thank you all the same.
@DanielKeep is inactive in Github for quite a long time, the best way is to ask him directly. However, I think he will not response. So I raise an issue here.

**Comment by DanielKeep** [comment]
No tool, just a text editor and several custom compose sequences.  I recall trying a few "ascii drawing" tools, but found all of them to be more time consuming to use than just doing it by hand.

This was a while ago, so I could be wrong, but I *believe* I used Sublime Text.  Oh, and if your editor supports it, use overwrite mode to keep things from moving around.  For compose key sequences, I use WinCompose.  Unfortunately, I built a new machine a while ago, and I lost my compose key file in the process.  I believe it was mostly sequences like `<Multi_key> <b> <d> <u> <r>` for "box draw up right" to produce `└`.

And time.  Quite a bit of time.  Good luck!

**Comment by tan-wei** [comment]
@DanielKeep Wow, thanks for your reply. I thought you would not reply here.

I've tried some ASCII drawing tools, they're not that handy and the results are not beautiful. So I feel intersting about the ASCII chart. Beautiful things always need much more time. Thanks for your advice.

The issue should be closed now.
