### ISSUE TITLE
"Macros in the AST" needs clarification

### ISSUE THREAD

**Issue by peter-kehl** [Veykril/tlborm#32]
Hi Lukas and friends,

Thank you for The Little Book of Rust Macros.

The first paragraph, the first list, the second and fourth paragraphs of https://veykril.github.io/tlborm/macros/syntax/ast.html need clarification. The following is quoting that page, with my comments prefixed with --:

... following forms (by way of examples):
-- please clarify that it's 4 forms, no classification into subforms
 *  `# [ $arg ]; e.g. #[derive(Clone)], #[no_mangle], …`
 *  `# ! [ $arg ]; e.g. #![allow(dead_code)], #![crate_name="blang"], …`
 *  `$name ! $arg; e.g. println!("Hi!"), concat!("a", "b"), …`
 *  `$name ! $arg0 $arg1; e.g. macro_rules! dummy { () => {}; }.`

... The latter two can be implemented with the second macro system that Rust offers, procedural macros.
-- Which latter two - the third and fourth form? Two paragraphs below it says that the "fourth is... not available to macros"!

The fourth is essentially a variation which is not available to macros. In fact, the only case where this form is used at all is with macro_rules! itself which, again we will come back to.
-- see the conflict above

**Comment by Veykril** [comment]
Oh that's a good catch, that's indeed a bit confusing haha. I'll take a stab at clarifying that later 👍

**Comment by Veykril** [comment]
Okay I rewrote the section slightly, https://github.com/Veykril/tlborm/commit/d0a1b6996e896378db9ee2012f179d2134e758bb, let me know if this clears up the misunderstandings you had or whether it needs more touch ups

**Comment by peter-kehl** [comment]
Lovely. Thank you.
