### ISSUE TITLE
a small bugs in `parsing` chapter

### ISSUE THREAD

**Issue by zjp-CN** [Veykril/tlborm#37]
Thank you for your updating work very much.

I'm [translating](https://github.com/zjp-CN/tlborm) your book into Chinese, and noticed the template code in  [function](https://veykril.github.io/tlborm/building-blocks/parsing.html#function) section of the final chapter doesn't work well.

the sixth line 
`$vis:vis fn $name:ident ( $( $arg_pat:ident : $arg_ty:ty ),* $(,)? )` 
should be `$vis:vis fn $name:ident ( $( $arg_name:ident : $arg_ty:ty ),* $(,)? )`

---

by the way: I'm looking forward to learn the awesome example in [method](https://veykril.github.io/tlborm/building-blocks/parsing.html#method) section :)

good luck

**Comment by Veykril** [comment]
Ah nice catch, I fixed it, thanks!
I'm unfortunately not sure when I'll be able to work on the method section as it is certainly more tricky then the rest
