### ISSUE TITLE
Confusion in discussion about `a` and `n` in macros-practical example

### ISSUE THREAD

**Issue by wpd** [Veykril/tlborm#52]
The example contains the statement:

>This changes the definition of `a` to:
```
let a = IndexOffset { slice: &self.mem, offset: n };
```
I don't see where `a` was defined prior to that statement.
Similarly, shortly after that, you wrote:
> Note that I've changed the order of the declarations of `n` and `a`, as well as wrapped them(along with the recurrence expression) in a block.
I don't see `n` or `a` in the code that precedes that.

**Comment by Veykril** [comment]
`a` and `n` are introduced in the code block after the `We need a branch to yield the initial values of the sequence; nothing tricky.` line. Needless to say, the variable names could and probably should be something more descriptive than `a` or `n`.

**Comment by wpd** [comment]
Note to self... don't press the "Comment" button in GitHub until you've gone to sleep, gotten up the next morning, and looked at the code again.  I now see that somehow during the night (without pushing any changes to GitHub), pixies snuck in and added some code to your example.  Today, I see:
```
let a = /* something */;
let n = self.pos;
```
I _swear_ that wasn't there last night! (It was).
I'm sorry for the noise.
