### ISSUE TITLE
Error in 2.2 Practical Introduction (decl macro)

### ISSUE THREAD

**Issue by matthiascy** [Veykril/tlborm#53]
Hi,

There is an error in chapter practical introduction of macro-by-example:
```rust
macro_rules! recurrence {
    ( a[n]: $sty:ty = $($inits:expr),+ ... $recur:expr ) => {
//                                     ^~~ changed
        /* ... */
    };
}
```
According to the Rust Reference: 

> `expr` and `stmt` may only be followed by one of: `=>`, `,` or `;`.

Only these three symbols are allowed after expression.

**Comment by Veykril** [comment]
This is intentional, the paragraph afterwards talks about this not being allowed.

> Success! ... or so we thought. Turns out this is being rejected by the compiler nowadays, while it was fine back when this was written. The reason for this is that the compiler now recognizes the ... as a token, and as we know we may only use =>, , or ; after an expression fragment. So unfortunately we are now out of luck as our dreamed up syntax will not work out this way, so let us just choose one that looks the most befitting that we are allowed to use instead, I'd say replacing , with ; works.
