### ISSUE TITLE
Recursion limit number is wrong

### ISSUE THREAD

**Issue by zjp-CN** [Veykril/tlborm#63]
> This is known as the syntax extension recursion limit and defaults to 32. If the 32nd expansion contains a syntax extension invocation, the compiler will abort with an error indicating that the recursion limit was exceeded.

Change `32` into `128` according to the number followed by the link [#![recursion_limit="…"] attribute](https://doc.rust-lang.org/reference/attributes/limits.html#the-recursion_limit-attribute) which is given after the mentioned quote.

I remember this number was correct in your version.

BTW: now I'm updating the Chinese version, and there are many modifications since  last time I did the translation :) But it's worth it, thank you for your work.

**Comment by Veykril** [comment]
Yes I have changed a lot of things, sorry :)
