### ISSUE TITLE
TT Bundling example doesn't compile

### ISSUE THREAD

**Issue by amab8901** [Veykril/tlborm#82]
[This](https://veykril.github.io/tlborm/decl-macros/patterns/tt-bundling.html) page has an example. It doesn't compile when I click "run". So if the example doesn't compile, then what's the point with reading the example? What's the point with reading about something that doesn't even work?

Please fix the example so that it actually compiles, and then the reader may actually start learning something from that example.

**Comment by Veykril** [comment]
Next time you report an issue be aware of your tone. The wording of this issue is completely unacceptable and if it wasn't a technical one I wouldn't have considered fixing it given how rude you were.

**Comment by amab8901** [comment]
> Next time you report an issue be aware of your tone. The wording of this issue is completely unacceptable and if it wasn't a technical one I wouldn't have considered fixing it given how rude you were.

I'm sorry if I came across as being rude. That wasn't my intention. My intention was to clearly communicate what the problem is and why it's a problem and what I think should be done to solve it, and why my proposed solution would be valuable to the reader. If you could rewrite the issue report that I made, how would you formulate it instead?

**Comment by Veykril** [comment]
Asking `What's the point` comes over as very aggressive, you are basically questioning why the chapter was written in the first place somewhat implying the chapter being completely pointless, thats what made it rather rude to me.

>  Please fix the example so that it actually compiles, 
is a very commanding tone

>and then the reader may actually start learning something from that example.
This goes back to my first point, implying the chapter as written is pointless

**Comment by amab8901** [comment]
> Asking `What's the point` comes over as very aggressive, you are basically questioning why the chapter was written in the first place somewhat implying the chapter being completely pointless, thats what made it rather rude to me.
> 
> > Please fix the example so that it actually compiles,
> > is a very commanding tone
> 
> > and then the reader may actually start learning something from that example.
> > This goes back to my first point, implying the chapter as written is pointless

Thank you for the advice. Due to my personality (INTJ), I have low awareness of when I'm being rude, and high awareness of flaws in systems, and high focus on pragmatism and low focus on emotions (especially that of other people). I appreciate your feedback and explanation to help me increase my awareness in this area. Please don't feel like I don't value the content you're producing. It's very valuable, but the more I focus on what can be improved, the harder it is to focus on the things that are already good. And the former is my primary focus due to my personality. 

I will try not to say "what's the point" in the future. If I say something in the future that you perceive as rude, then:
1) understand that I have no bad intentions and I have a naturally low awareness of these things
2) feedback and explanations on what I can do better in this area are appreciated, as is the work that you do with the Little Book of Rust Macros
